[tool.poetry]
name = "tpc-server"
version = "0.1.0"
description = ""
authors = ["Badmajor <v.balonkin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
aiosqlite = "^0.20.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
